controllers:
  resource: ../src/Controller/
  type: attribute

delete_image:
  path: /suppression/image/{imageId}
  controller: App\Controller\ProductsController::deleteImage
  methods: [DELETE, GET]
